import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Random: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "potato pasta" });
  const mutation = api.form.create.useMutation();
  return (
    <>
      <Head>
        <title>Upload Photos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Do something I guess
          </h1>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
        <button className="rounded-xl text-yellow-200 bg-indigo-500 gap-12 px-4" onClick={() => mutation.mutate() }>Click me!</button>
        <div className="text-xl text-white rounded-xl">
          {mutation?.data?.path ? mutation.data.path : '...'}
          {mutation?.data?.picture ? JSON.stringify(mutation.data.picture, null, 2) : '_'}
        </div>
        <div className="text-xl text-green-400 rounded-xl">{mutation?.error?.message ? mutation.error.message : '...'}</div>
      </main>
    </>
  );
};

export default Random;
